#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t mk"
$L "   __  __    ___    _  __  _____   _____  ";
$L "  |  \/  |  / _ \  | |/ / | ____| | ____| ";
$L "  | |\/| | | | | | | ' /  |  _|   |  _|   ";
$L "  | |  | | | |_| | | . \  | |___  | |___  ";
$L "  |_|  |_|  \___/  |_|\_\ |_____| |_____| ";
$L "                                          ";

$L "Welcome to Android `getprop ro.build.version.release` / MoKee-`getprop ro.mk.version`";
