#!/sbin/sh
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ui_print by Chainfire
OUTFD=$(/sbin/ps | /sbin/grep -v "grep" | /sbin/grep -o -E "update_binary(.*)" | /sbin/cut -d " " -f 3)
ui_print(){
if [ $OUTFD != "" ];then
	echo "ui_print ${1} " 1>&$OUTFD
	echo "ui_print " 1>&$OUTFD
else
	echo "${1}"
fi
}

# Commerce patch
ui_print "Patching $1"
/tmp/xdelta3 -D -R -d -s $1 $2 $3

# Only replace file if patching succeeds 
if [ -f $3 ];then
	/sbin/rm $1
	/sbin/rm $2
	/sbin/mv $3 $1
fi

