#!/sbin/sh
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# ui_print by Chainfire
OUTFD=$(/sbin/ps | /sbin/grep -v "grep" | /sbin/grep -o -E "update_binary(.*)" | /sbin/cut -d " " -f 3)
ui_print(){
if [ $OUTFD != "" ];then
	echo "ui_print ${1} " 1>&$OUTFD
	echo "ui_print " 1>&$OUTFD
else
	echo "${1}"
fi
}

# Commerce patch
ui_print "Patching $1"
/system/bin/xdelta3 -D -R -d -s $1 $2 $3

# Only replace file if patching succeeds 
if [ -f $3 ];then
	/sbin/rm $1
	/sbin/mv $3 $1
fi
/sbin/rm $2
