#!/sbin/sh
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ui_print by Chainfire
OUTFD=$(/sbin/ps | /sbin/grep -v "grep" | /sbin/grep -o -E "update_binary(.*)" | /sbin/cut -d " " -f 3)
ui_print(){
if [ $OUTFD != "" ];then
	echo "ui_print ${1} " 1>&$OUTFD
	echo "ui_print " 1>&$OUTFD
else
	echo "${1}"
fi
}

# Get ro.modversion from build.prop
CUR_VER=`/sbin/cat /system/build.prop | /sbin/grep "ro.modversion" | /sbin/cut -d"=" -f2`

# Compare versions, if does not match, exit with error
if [ "$1" == "$CUR_VER" ];then
	ui_print "Versions match..."
	exit 0
else
	ui_print "Versions mismatch..."
	ui_print "Aborting..."
	/sbin/rm /tmp/verifier
	/sbin/umount /system
	exit 1
fi

