#!/sbin/sh
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# ui_print by Chainfire
OUTFD=$(/sbin/ps | /sbin/grep -v "grep" | /sbin/grep -o -E "update_binary(.*)" | /sbin/cut -d " " -f 3)
ui_print(){
if [ $OUTFD != "" ];then
	echo "ui_print ${1} " 1>&$OUTFD
	echo "ui_print " 1>&$OUTFD
else
	echo "${1}"
fi
}

# Get ro.modversion from build.prop
CUR_VER=`/sbin/cat /system/build.prop | /sbin/grep "ro.modversion" | /sbin/cut -d"=" -f2`

# Compare versions, if does not match, exit with error
if [ "$1" == "$CUR_VER" ];then
	ui_print "Versions match..."
	exit 0
else
	ui_print "Versions mismatch..."
	ui_print "Aborting..."
	/sbin/rm /tmp/verifier
	/sbin/umount /system
	exit 1
fi

